### PR TITLE
Fix concurrency issues when loading templates

### LINKED ISSUE #339: 🐛 [Bug]: request fail before the template is available
### Bug Description

Observable behavior (recalled from my memory):

/layout template not found

### How to Reproduce

I don't know! I only saw it once.

the actual application in question is https://codeberg.org/vnpower/pixivfe
where i

1. `go run .`
2. visit `http//localhost:8282/` in browser

I couldn't get it to reproduce again.

I suspect this is a race condition

### Expected Behavior

The server should not respond to requests if the templates are not compiled yet.

### Fiber Version

v2.52.0

### Code Snippet (optional)

_No response_

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

### PR DESCRIPTION
**Pull request by gaby**
- Expanded benchmarks for all the template engines
- Added support for benchmarking with/without asserts
- Added support for benchmarking concurrency of each engine
- Fixed several concurrency issues exposed by `b.RunParallel()` benchmarks
- Updated the `golangci-lint` workflow to add annotations.
- Updates to template.go
- Added go1.22 to test matrix
- Migrated handlebars to use https://github.com/mailgun/raymond
- Fixes #328 #329 
- Updated golangci-lint to v1.56.2 and fixed the issues

Fixes #339

### CODE REVIEW

File: ace/ace_test.go [hunk 1]
```diff
@@ -197,34 +198,125 @@ func Benchmark_Ace(b *testing.B) {
...
+		bb.ResetTimer()
+		for i := 0; i < bb.N; i++ {
+			var buf bytes.Buffer
+			err := engine.Render(&buf, "simple", map[string]interface{}{
+				"Title": "Hello, World!",
+			})
 
-		require.NoError(b, err)
-		require.Equal(b, expectExtended, trim(buf.String()))
+			require.NoError(b, err)
```
Comment (nickajacks1) [inline ace/ace_test.go:236]: have you found that there is a difference between asserting within the bench loop and outside? I've always seen the assert outside the loop.

File: amber/amber_test.go [hunk 2]
```diff
@@ -175,35 +177,127 @@ func Benchmark_Amber(b *testing.B) {
 	engine.AddFunc("isAdmin", func(user string) bool {
 		return user == "admin"
```
Comment (nickajacks1) [inline amber/amber_test.go:178]: replace `"admin"` with `admin`

File: django/django.go [hunk 3]
```diff
@@ -27,56 +27,39 @@ type Engine struct {
...
+// This helper function is used to avoid duplication in public constructors.
+func (e *Engine) initialize(directory, extension string, fs http.FileSystem) {
+	e.Engine.Left = "{{"
+	e.Engine.Right = "}}"
+	e.Engine.Directory = directory
+	e.Engine.Extension = extension
+	e.Engine.LayoutName = "embed"
+	e.Engine.Funcmap = make(map[string]interface{})
+	e.autoEscape = true
+	if fs != nil {
```
Comment (nickajacks1) [inline django/django.go:39]: won't e.Engine.FileSystem be nil with or without this check?

File: django/django_test.go [hunk 4]
```diff
@@ -349,65 +349,251 @@ func Benchmark_Django(b *testing.B) {
...
-			err = engine.Render(&buf, "extended", map[string]interface{}{
+			//nolint:gosec,errcheck // Return value not needed for benchmark
+			_ = engine.Render(&buf, "extended", map[string]interface{}{
 				"User":        admin,
 				"Invalid_Key": "Don't return error from checkForValidIdentifiers!",
 			}, "layouts/main")
 		}
+	})
+
+	b.Run("simple_asserted", func(bb *testing.B) {
```
Comment (nickajacks1) [inline django/django_test.go:408]: I wonder if these benchmarks could be put in a common test package to ensure consistency

File: template.go [hunk 5]
```diff
@@ -99,6 +109,40 @@ func (e *Engine) Layout(key string) IEngineCore {
...
+
+// Loaded returns true if templates are loaded
+func (e *Engine) Loaded() bool {
+	e.Mutex.RLock()
+	defer e.Mutex.RUnlock()
+	return e.loaded
+}
+
+// SetLoaded sets the loaded status
+func (e *Engine) SetLoaded(enabled bool) IEngineCore {
```
Comment (nickajacks1) [inline template.go:133]: Was there a particular reason SetLoaded is the only operation with a non-locking option?

**Review by nickajacks1 — COMMENTED** [review]
Looks good, just a few comments+questions.
Not too familiar with this project or templating, so I may have missed stuff.

File: ace/ace_test.go (hunk 1 above)
Comment (gaby) [reply ace/ace_test.go:236]: Asserting outside the loop only checks the LAST value from the loop. Asserting inside the loop exposed that values were changing between loops since the template were not finished rendering.

This was fixed by adding the mutex in `Render()`.

File: template.go (hunk 5 above)
Comment (gaby) [reply template.go:133]: `SetLoaded` is only called from `Load()` which already acquires a Lock for the full scope of the call.

File: .golangci.yml [hunk 6]
```diff
@@ -12,75 +11,61 @@ output:
...
-      - experimental
-      - opinionated
     disabled-checks:
-      - hugeParam
-      - rangeValCopy
+      - ifElseChain
 
   gofumpt:
-    module-path: github.com/gofiber/template
+    module-path: github.com/gofiber/fiber
```
[the remark this answers is not in the document]
Comment (gaby) [reply .golangci.yml:43]: Oops

File: django/django_test.go (hunk 4 above)
Comment (gaby) [reply django/django_test.go:408]: Thought about that but some are different for some of the engines. The expected values are also different

File: amber/amber_test.go (hunk 2 above)
Comment (gaby) [reply amber/amber_test.go]: Fixed

File: django/django.go (hunk 3 above)
Comment (gaby) [reply django/django.go]: Yeah, the check has 0 use. It either is nil or has a filesystem

File: template.go [hunk 7]
```diff
@@ -38,59 +42,65 @@ type Engine struct {
...
+	e.Mutex.Lock()
+	defer e.Mutex.Unlock()
 	e.Left, e.Right = left, right
 	return e
 }
 
 // FuncMap returns the template's function map.
-func (e *Engine) FuncMap() map[string]interface{} {
+func (e *Engine) FuncMap() map[string]any {
+	e.Mutex.RLock()
```
[the remark this answers is not in the document]
Comment (gaby) [reply template.go:95]: Yeah, that's the purpose. When I started playing with the `RunParallel()` benchmarks it exposed a lot of concurrency issues since it runs the benchmark using concurrent goroutines

**Review by nickajacks1 — APPROVED** [review]

File: template.go [hunk 8]
```diff
@@ -38,59 +42,65 @@ type Engine struct {
 	Extension string
 	// layout variable name that incapsulates the template
 	LayoutName string
-	// determines if the engine parsed all templates
```
Comment (ReneWerner87) [inline template.go:41]: we need to customize the version of the template core and mark it as breaking because we have removed the previously exposed properties

- [ ] increase the template core version with a major jump and change the pkg go.mods

**Review by ReneWerner87 — CHANGES_REQUESTED** [review]
adjustments due to the versions still need to be done

**Comment by gaby** [comment]
> adjustments due to the versions still need to be done

All done

**Comment by gaby** [comment]
@ReneWerner87 @efectn @sixcolors Breaking changes have been removed :-)

**Review by ReneWerner87 — APPROVED** [review]
